[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-ws = "0.3.0"
bytestring = "1.3.1"
futures-util = "0.3.31"
serde = { version = "1.0.212", features = ["derive"] }
serde_json = "1.0.132"
